### ISSUE TITLE
Support Cocoapods along side Carthage and SPM

### ISSUE THREAD

**Issue by saragiotto** [surpher/PactSwift#103]
# 🗣 Context

Is it possible to add support to installation via cocoapods?

# 📝 Notes

Current project does not have SPM nor Carthage.

**Comment by surpher** [comment]
Sorry, but I don't see that happening, but contributions are welcome. 
The "support" for Carthage has been dropped more than a few months back when it was dropping transient dependencies' binaries. 

There's also a very big rewrite happening right now (PactSwift 2.x) to support Swift's concurrency and also completely dropping Xcode projects out of this repo. That means only SPM will be supported going forward.

My suggestion to you would be to create your own `PactSwift.xcframework` and use it in your project.
