### ISSUE TITLE
Question: Rest vs GraphQL services

### ISSUE THREAD

**Issue by mstana** [surpher/PactSwift#105]
# ❔ Question

Is it possible to test GraphQL queries with PactSwift?

# 💬 Context

I am trying to use PactSwift library to test multiple sources. First I have worked with REST API and I was able to successfully create Request/Response test. Now I am trying to do the same but anytime I am trying to run request I am getting general error: `failed: caught error: "The operation couldn’t be completed. (PactSwiftMockServer.VerificationError error 0.)`.

GraphQL queries contains complex bodies - can this be a problem?

Thank you for any help.

# 🤝 Relationships

- None.

**Comment by surpher** [comment]
Sorry but haven't focused on GraphQL using PactSwift. There seem to be a few people in the `#pact-swift` channel in `pact-foundation.slack.com` [Slack](https://docs.pact.io/help/how_to_ask_for_help) workspace that asked GraphQL related questions. I believe they've managed to get it working. Might be worth asking there.

**Comment by mstana** [comment]
Thank you for your response @surpher. I found the problem in my implementation. Long story short - make sure that body of the request-response that is JSON has also correct HTTP headers with Content-Type. That was my problem.

**Comment by surpher** [comment]
Great! Thanks for sharing how you've solved it. Much appreciated.
