### ISSUE TITLE
Task: Unit tests for swift concurrency refactor

### ISSUE THREAD

**Issue by surpher** [surpher/PactSwift#115]
# ❕ Problem Statement

This fork has been spun up for specific needs of a project IBA is involved in. Therefore some of the code is not tested properly.

# 💬 Task Description

- Fix any existing failing unit tests
- Write "e2e" tests verifying `Pact` contract is written and assert it contains expected elements  
(eg: https://github.com/surpher/PactSwift/blob/main/Tests/Services/PactContractTests.swift)

# 📝 Notes

Branch off of https://github.com/surpher/PactSwift/tree/feat/v2.0.0

# 👩‍🔧 Technical Design Notes

# 🤝 Relationships

- Other Related Issues: #xxx, #yyy

**Comment by jasunde** [comment]
@surpher I began looking at this issue. Can't say for sure that I'll have much time to work on it, but I've found a few moments lately. I'm trying to follow the guidelines for contributing (haven't done it before) so please excuse if this is newbie behavior. 

This might be a good use case for the inline snapshot testing of this library: https://github.com/pointfreeco/swift-snapshot-testing So I made a quick and dirty little PR on my own fork to show you [what it might look like](https://github.com/jasunde/PactSwift/pull/2/files#diff-6a13437867c3a54f040d7fb57f1cc2fcba9a38d9c048a9fc89703cc16197d813R61:~:text=assertInlineSnapshot). That json snippet is generated by the test and recorded inline.

What do you think? The randomness in the key property makes testing the whole interaction at once in this way impossible unless we could control for that dependency.

Happy to take a similar approach to how it was done before as well.

**Comment by surpher** [comment]
Awesome, thanks for taking time to look into this! Very much appreciated. 
I will certainly have a look. I don't mind bringing in snapshot testing if it helps with quality and stability of the project. 👍

The only thing I'd try and stick to is not bringing in _too many_ dependencies - for the sake of maintainability. There's an [ADR-004](https://github.com/surpher/PactSwift/blob/feature/swift-concurrency/Documentation/ADRs/ADR-004-Dependencies-management.md) about that, that needs to be followed up with a new one as 004 is outdated with SPM's evolution.

There's a [CONTRIBUTING.md](https://github.com/surpher/PactSwift/blob/feature/swift-concurrency/CONTRIBUTING.md) file that describes how to contribute and open a pull request. 
But I think it needs a bit of tweaking. Not that the `main` brach expects requires [signed commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits). 

I too have done some cleaning up this last weekend and there's a huge refactor happening on branch `feature/swift-concurrency` taking a deep dive into async await land.

Oh and [this is going to happen](https://github.com/surpher/PactSwift/discussions/122) soon so if you're keen and willing to continue with contributions will work with you so it's not too disruptive.

**Comment by jasunde** [comment]
@surpher A few questions for you as I work through converting PactContractTests

- Seems like a couple matchers are not implemented yet. What should I do with those? Here are their previous names: 
  - `EachKeyLike`
  - `FromProviderState`
- There are a number of tests that have arrays with mixed matchers. For example see `testBugExample()`. Was that option deprecated?
- `PactBuilder.path` property does not accept a matcher. Was that option deprecated?

**Comment by surpher** [comment]
@jasunde To be completely honest? I'm not sure anymore. Been a very long while since I've touched this project. As already stated in discussions.

Ignore missing matchers for now. 
I'll have a closer look at the other two points in the next day and get back to you. 

Also, if you'd be more comfortable taking these offline, I'm always logged into [Pact-Foundation's Slack workspace](https://docs.pact.io/help/how_to_ask_for_help#3-find-the-appropriate-slack-channel-for-your-question). Same(ish) handle: `@surpher (pact-swift)`. If not, don't worry about it. 👍
