### ISSUE TITLE
Null matcher

### ISSUE THREAD

**Issue by surpher** [surpher/PactSwift#14]
## Overview
Sometimes explicitly matching to `null` in JSON is required.

## Task
Provide a matcher that tells Mock Service to return `{ ... "key": null ...}` and match for `Null` as value.

Suggested matcher signature:

`MatchNull()`

Rule declaration:

```swift
{ "match": "null" }
```

Mock server will respond with:

```json
{
  "someKey": null
}
```

### Pact example:

DSL:

```swift
.willRespond(
  status: 200,
  body: [
    "some_value": MatchNull()
  ]
)
```

Example Pact output:

Important bits are `{ "match":"null" }` under `matchingRules`  
and `"some_value": null` under `"body"`:

```json
{
    "somePactKeys": "somePactValuesOrObjects",
    "interactions": [
        {
            "somePactKeys": "somePactValuesOrObjects",
            "response": {
                "somePactKeys": "somePactValuesOrObjects",
                "status": 200,
                "body": {
                    "some_value": null
                },
                "matchingRules": {
                    "body": {
                        "$.some_value": {
                            "matchers": [
                              { "match": "null" }
                            ]
                        }
                    }
                }
            }
        }
    ]
}
```

### Discussion

Follow [pact-specification v3](https://github.com/pact-foundation/pact-specification/tree/version-3#add-more-specific-type-matchers) paragraph describing behaviour for _More Specific Type Matchers_.

**Comment by huwr** [comment]
Do you mean `{ "match": "null" }` or `{ "match": null }`?

**Comment by surpher** [comment]
Hi @huwr , I've updated the description of how I see it. Pact-specification is specific about how a rule is defined in the Pact contract. As for the name of the matchers as `MatchNull()`... I'm flexible, as long as the lot is the same.

I believe a custom encodable in [AnyEncodable.swift](https://github.com/surpher/PactSwift/blob/master/Sources/Definitions/AnyEncodable.swift) and [PactBuilder.swift](https://github.com/surpher/PactSwift/blob/master/Sources/Definitions/PactBuilder.swift) edit to handle `null` is needed?

**Comment by surpher** [comment]
```swift
// Swift
Matcher.MatchNull()

// Obj-C
[[PFMatcherNull alloc] init];
```
