### ISSUE TITLE
XCUI (out-of process) support?

### ISSUE THREAD

**Issue by rastersize** [surpher/PactSwift#25]
# 🗣 Context

I’m looking at using Pact for XCUI tests and since this project [appears to be the next generation](https://github.com/DiUS/pact-consumer-swift/issues/95#issuecomment-631213618), with Pact v3 support, I was looking to see if I could try it out. However I couldn’t find anything around how this would work with out-of process tests. Like when running XCUI tests. Since the project makes a mention of not using the Ruby Mock Service in the readme I also wonder if this is something that PactSwift doesn’t aim to provide.

So, I’m wondering if it already works, is planned or something that PactSwift doesn’t aim to solve? Thank you!

# 💬 Narrative

When writing UI automation tests using XCUI
I want to be able to use Pact
So that the application under test uses the contracts

# ✅ Acceptance Criteria

**GIVEN** An XCUI test
**WHEN** There’s a network call
**THEN** It should use a response from Pact

**Comment by surpher** [comment]
Hi @rastersize 
Out of process wasn't the aim for PactSwift or develop PactSwift for UI testing. The idea of Pact is to the interaction between provider and consumer in isolation at unit test level. Eg, test your network layer requests (in isolation) against provider's response, and the same on the other end ensuring a contract.

I did think about a setting to swap between the in-process and a standalone Mock Service (eg pact-ruby-standalone, or any other Mock Service) for a bit, but dropped it. This would probably also come in handy when testing macOS apps where you wouldn't necessarily want to flag your app as a server in app entitlements.

There is a [PACT Mock Server CLI](https://docs.pact.io/implementation_guides/rust/pact_mock_server_cli/) that could potentially serve as your standalone Mock Service (v3)? First you'd run your pact unit tests that would generate your pact.json file. Then when spinning up your UI tests, you'd first feed your pact.json into the Mock Server CLI and run your UI tests against it? Then shut it down? Maybe that could work? But this might introduce similar/same issues we were experiencing with pact-consumer-swift and that we were trying to avoid with v3 implementation (eg. fiddling about with pre/post-test actions to spin up the mock service etc).

**Comment by rastersize** [comment]
Thank you for the detailed reply @surpher!

After some additional experimentation I’ve found a way to use PactSwift from a XCUI test 🎉  It involves passing a mapping (endpoint -> Pact mock server) and a custom `URLProtocol`. Very similar to how [SBTUITestTunnel](https://github.com/Subito-it/SBTUITestTunnel) works. If you’re interested I can try to write something up once I’ve cleaned up my code a bit?

**Comment by surpher** [comment]
That would be fantastic if you could share your approach @rastersize. Thank you!
Perhaps in a demo project on GitHub that we can then link to from our readme files?
