### ISSUE TITLE
Bug: .a files don’t seem to be using git-lfs

### ISSUE THREAD

**Issue by rastersize** [surpher/PactSwift#26]
# 🌎 Environment

- Git: 2.28.0
- git-lfs: 2.11.0 (GitHub; darwin amd64; go 1.14.2)

# 💬 Description

The `libpact_mock_server.a` files appear to be added directly to the git repo and not git-lfs. Although the `.gitattributes` file notes that they should be using git-lfs.

# 🦶 Reproduction Steps

```shell
$ git clone https://github.com/surpher/PactSwift
Cloning into 'PactSwift'...
remote: Enumerating objects: 155, done.
remote: Counting objects: 100% (155/155), done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 1720 (delta 81), reused 83 (delta 33), pack-reused 1565
Receiving objects: 100% (1720/1720), 41.60 MiB | 58.20 MiB/s, done.
Resolving deltas: 100% (995/995), done.
Encountered 2 file(s) that should have been pointers, but weren't:
	Resources/iOS/libpact_mock_server.a
	Resources/macOS/libpact_mock_server.a

$ cd PactSwift
# Check if files are LFS pointers, or real files on disk:
$ git show HEAD:Resources/macOS/libpact_mock_server.a
!<arch>
#1/12           0           0     0     0       3514948   `
__.SYMDEF […]

$ git status -sb
## master...origin/master
 M Resources/iOS/libpact_mock_server.a
 M Resources/macOS/libpact_mock_server.a

$ git lfs fetch --all
fetch: 2 object(s) found, done.
fetch: Fetching all references...

$ git status -sb
## master...origin/master
 M Resources/iOS/libpact_mock_server.a
 M Resources/macOS/libpact_mock_server.a

$ git show HEAD:Resources/macOS/libpact_mock_server.a
!<arch>
#1/12           0           0     0     0       3514948   `
__.SYMDEF […]
```

# 🤔 Expected Results

- Expected the `git clone` to work without any warnings.
- Expected `git show HEAD:Resources/macOS/libpact_mock_server.a` and git show HEAD:Resources/iOS/libpact_mock_server.a` to both show a pointer file. E.g.

  ```
  version https://git-lfs.github.com/spec/v1
  oid sha256:ff65404ef9ef5bad31a5b7fe7469cb24c831c03741046a20b860ba7ec8e47c20
  size 65368
  ```
- `git status` to report no changes after a fresh clone.

# 😲 Actual Results

- The `.a` files appear to have been added to git’s object storage instead of using git-lfs.
- The PactSwift git clone is always in a “dirty” state.

**Comment by rastersize** [comment]
I wonder if something like this needs to be done:

https://github.com/git-lfs/git-lfs/wiki/Tutorial#migrating-existing-repository-data-to-lfs

Or if there’s something I’m missing in my setup?

I also tried running:

```shell
$ cd PactSwift
$ git lfs install
$ git lfs fetch (--all)
$ git lfs checkout
```

Unfortunately that didn’t help either.

**Comment by surpher** [comment]
Thanks for reporting this. Have you found a solution in the mean time? If not, I'll look into it.

**Comment by rastersize** [comment]
@surpher I was able to work around it for now by forking the repo (internally to our GHE instance) and adding the files to “plain” git. Which obviously isn’t ideal hehe

**Comment by surpher** [comment]
Hey @rastersize . 
I think I've managed to move the `.a` files to LFS properly now. 
Can you run a fresh `git clone` to confirm?

<img width="837" alt="Screen Shot 2020-09-02 at 1 34 36 pm" src="https://user-images.githubusercontent.com/1733327/91929184-2e04ed80-ed21-11ea-99f0-4feba267309e.png">

**Comment by rastersize** [comment]
Thank you @surpher! Tried again and it looks good now for both macOS and iOS 👍
