### ISSUE TITLE
Task: Xcode 12 issue - `libpact_mock_server.a` missing arm64 architecture

### ISSUE THREAD

**Issue by surpher** [surpher/PactSwift#27]
# ❕ Problem Statement

Xcode 12 is about to be released and compiler is building for the upcoming arm64 architecture. When having command line tools set to Xcode 12 and running `carthage build [--no-skip-current]`, the build fails with:

```
error: The linked library 'libpact_mock_server.a' is missing one or more architectures required by this target: arm64. (in target 'PactSwift_macOS' from project 'PactSwift')
```

# 💬 Task Description

Build new libpact_mock_server.a static libs that include arm64 architecture.
DTK poking it’s head up when building with Xcode 12 due to new arm64 architecture missing in `libpact_mock_server.a`. 

# 👩‍🔧 Technical Design Notes

Carthage `v0.35.0`
Xcode 12 beta 6, 
Xcode 12 Command line tools

# 🤝 Relationships

- Other Related Issues: 
https://github.com/rust-lang/rustup/issues/2413
https://github.com/rust-lang/rust/issues/73908

**Comment by rastersize** [comment]
This is likely going to be difficult until Carthage adds XCFrameworks support: https://github.com/Carthage/Carthage/issues/3019

**Comment by surpher** [comment]
Correct. If anyone notices it being sorted out, a PR is welcome. I will commit a script/documentation that will run cargo build commands and replace the existing binaries. 

On top of that, having these binaries wrapped in a XCFramework might be a better idea altogether.

**Comment by surpher** [comment]
Got fed up with waiting for Carthage and used @rastersize provided bash script 
Script added to PactSwift with commit 473f298.
