### ISSUE TITLE
Task: Sanity check the written Pact contract

### ISSUE THREAD

**Issue by surpher** [surpher/PactSwift#35]
# ❕ Problem Statement

`libpact_mock_server.a` is a dependency brought into `PactSwift` that stands in place of a mock server when running our consumer Pact tests and is responsible for writing the Pact contract file to disk. This binary is built from [Rust codebase](https://github.com/pact-foundation/pact-reference/tree/master/rust/pact_mock_server_ffi). It has happened that we have seen unexpected behaviour when passing data to `libpact_mock_server` and asking it to write a final Pact file for us. `pact_mock_server` runs it's own unit tests but it because of the nature of Pact, there may be a lot of cases that are not covered.

It would be good to uncover unexpected behaviour so we can avoid breaking `PactSwift`'s features. And help improve the project.

# 💬 Task Description

- Write tests/unit tests that generate a Pact file, reads from the generated file and asserts some values"
-- Description of an interaction(s) is as expected
-- Contains the expected values for provider state
-- Interaction contains the expected number of matchers
-- Interaction contains the expected number of generators

# 👩‍🔧 Technical Design Notes

- A couple of simple unit tests to cover the important parts of Pact file
- Read the generated file and run through `JSONDecoder()`
- The model to decode into can be tightly coupled to the tests that are written so it's easier to deal with `JSONDecoder()`
- Could leverage ` PactMockServiceTests.testMockService_Writes_PactContract()`

# 🤝 Relationships

- Other Related Issues:

**Comment by huwr** [comment]
You might need to make the `libpact_mock_server.a` into an XCFramework

**Comment by surpher** [comment]
It's a binary built from Rust code. It should have its own unit tests. Because it accepts the Pact file that it then slightly modifies when writing the file to disk, it would be good to have a couple of tests that would pick up the JSON file written by libpact_mock_server and assert a few critical things are written to the file. (eg. number of interactions, description fields, number of matchers,...). 

Creating an XCFramework would be good, but not part of this. Would you want to have a look at that?

**Comment by huwr** [comment]
Oh yes. Sorry. Using an XCFramework might be important for when you want to support Mac Catalyst and ARM macOS, I think. Probably needs to be a different issue though

**Comment by surpher** [comment]
It will be. I believe it will be the way to go going forward. Raising a separate issue for it, with decent idea and description what needs doing, would come as a result of one of the "look into alternative approaches to using big binaries" issues already opened.

**Comment by surpher** [comment]
Resolved with 9d88d47
