### ISSUE TITLE
Task: Move Build Phase scripts into script files

### ISSUE THREAD

**Issue by surpher** [surpher/PactSwift#43]
# ❕ Problem Statement

macOS target contains a couple of Build Phase scripts that are written in the Build Phase themselves. This is not ideal and should be pulled out into a script file.

# 💬 Task Description

Pull out the scripts in Build Phases into script files and move into `/Scripts/BuildPhases`:

Targets: 
- [ ] `PactSwift_macOS` 
- [ ] `PactSwift_iOS`

BuildPhases:
- [ ] `Cargo build (libpact_mock_server.a)`
- [ ] Move the "check for rust" block of code in `./Scripts/build_file_list_and_swiftlint` file into it's own script file to be individually referenced from either a BuildPhase or GitHub workflow step

# 👩‍🔧 Technical Design Notes

- No scripts that are called from Build Phase are to install anything - it should only check for availability of the tools and stop the build (eg: _non zero return_ from script) if required tools are missing, and clearly display what the problem is.
- Build Phase script should reference the script file to run
- See Build Phase `Swiftlint` and `./Scripts/BuildPhases` for guidance
- Script filenames to not contain extension (eg. `.sh`) as first line in the script should imply it's a shell script.

# 🤝 Relationships

- Other Related Issues/PRs: #41

**Comment by iAshishChauhan** [comment]
Hey, I would like to give it a shot! Can you please assign this to me?

**Comment by surpher** [comment]
Thanks! 👍

**Comment by surpher** [comment]
I have made some minor changes to existing `PactSwift_macOS` scheme and its Build Phases in #45.
