### ISSUE TITLE
Add port configuration for MockServer

### ISSUE THREAD

**Issue by georgescumihai** [surpher/PactSwift#50]
# 🗣 Context

URL Signing with HMAC not possible with random port.
The signature will be correctly calculated but that means the mock server will have to have a random port as well.
This makes the testing against the Provider a lot more complicated.

# 💬 Narrative

When creating a pact test.
I want to have a configurable base url.
So that when testing the pacts against your BE, you can use a fix address for the mock server.

# 📝 Notes

If the port is configurable, the entire issue is handled. With the possibility that `create_mock_server` function fails if the port is already used, but that is something easy to work around.

# 🎨 Design

MockService should be able to have the port configurable. And pass that configuration when `MockServer` is created.

Right now the mockServer is created like this `mockServer = MockServer()`.
And `sockerAddress` and `port` are private variables of MockServer.

Extend the initializer for `MockService` to pass the dependencies.
Extend the `setup(pact:protocol:completion:)` and `finalize(pact:completion:)` functions to pass the dependencies, or add a initializer for `MockServer` to pass the dependencies.

# ✅ Acceptance Criteria

**GIVEN** A pact test. 
**WHEN** When running it.
**THEN** The baseUrl of the mockServer is always the same between test runs.

**Comment by surpher** [comment]
Thanks for raising this @georgescumihai. 
I've opened up a PR to address this issue. Would you mind giving it a go on the branch and check whether it solves it for you?

**Comment by surpher** [comment]
Implemented in [`v0.3.5`](https://github.com/surpher/PactSwift/releases/tag/v0.3.5)

**Comment by georgescumihai** [comment]
Thanks
