### ISSUE TITLE
Bug: MockServer build failing after MacOS (Big Sur) update

### ISSUE THREAD

**Issue by thomas-br** [surpher/PactSwift#62]
# 🌎 Environment

 - Xcode: 12.3
 - Platform: iOS 14.3
 - Version/Release: 0.3.4/0.3.5
 - Dependency manager: SPM

# 💬 Description

I was able to successfully setup PactSwift into my project. After the last MacOS update, the mockserver rust build, which is done as described in the docs through a script build phase, fails.

I updated rust/rustup and cargo-lipo to the newest version, even reinstalled them.

# 🦶 Reproduction Steps

MacOS 11.1 & build for ios (x86_64-apple-darwin)

1. Run Test build which executes the `build-spm-dependency ios` script
2. Observe the error

# 🤔 Expected Results

Successful build of the libpact_mock_server.a file 

# 😲 Actual Results

Error during rust build

## 🌳 Logs

```
error: linking with `cc` failed: exit code: 1
[...]
= note: ld: library not found for -lSystem
             clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## 📄 Stack Traces

`N/A`

# 🤝 Relationships

- Related PRs or Issues: #xxx, #yyy

**Comment by surpher** [comment]
Thanks for reporting! Will need to forward this to [pact-foundation/rust](https://github.com/pact-foundation/pact-reference)!

**Comment by surpher** [comment]
In the mean time, I wonder if a binary built for `x86_64` on a Catalina machine and copied to macOS 11 would work? Very very clumsy though. 
What that script is doing is really just building the fresh "portable" binary for you and replaces the "dud" binary in `/Resources` so there's no need for Git-LFS and we're saving on bandwidth and hosting. 

If you don't have any macOS 10 machines around you could potentially automate it via a GitHub Action on macOS 10.15 maybe (I'm not sure/aware of any size limits or cost though)? Build the binary, expose it as an artefact once it's built and you can transfer it to where you need it? 

Just thinking publicly here how to get around this problem until tools and dependencies catch up. (mind you, lots of my ideas are terrible 😂 )

**Comment by thomas-br** [comment]
I will try at least. Would it also work with the binary in the history of this repository?
Or were there changes in the meantime after it was changed to the build-on-the-fly?

**Comment by surpher** [comment]
It has changed as mock_sever fixed bugs. And I removed them from the repo history due to Git-LFS storage and bandwidth cost. 

If you're using carthage, you'll need to edit and remove the script in /Carthage/checouts so it doesn't try and build it again. Similar in SPM land. 

Please let me know if you manage to get it running and I might add a flag in order to skip building rust lib. So at least the builds won't fail where there's no need if one sorted out the binaries manually. I still don't have any machines running BigSur though but I'll see what I can do.

**Comment by surpher** [comment]
I've updated one of my Macs to BigSur and managed to successfully build and run a demo project using PactSwift via SPM.

As Build Phases run very isolated, the PATH is not full as if you were to run the commands/script in your terminal. What was missing is in the Build Phase that builds the lib, you need to specify the `PATH` to where `cc` lives. In my case was in `/usr/bin`.

This is the line I added just before `build-spm-dependency` script is being called:
```shell
export PATH="$HOME/.cargo/bin:/usr/bin:$PATH"
```

`lib pact_mock_server.a` builds successfully and tests execute as expected. 

I will update the documentation and example project with the above. 
Please let me know if that sorts out your issue too.

**Comment by thomas-br** [comment]
Thanks, works for me 👍
