### ISSUE TITLE
`willRespondWith` is not allowing me to have a nil value in the body

### ISSUE THREAD

**Issue by tsfischer** [surpher/PactSwift#74]
# 🌎 Environment

 - Xcode: 13.0
 - Platform: macOS
 - Version/Release: 0.10
 - Dependency manager: SPM

# 💬 Description

I'm attempting to mock out an error response which contains a nil field but it isn't working, logging the message that the body is not encodable.

# 🦶 Reproduction Steps
```
let errorResponseBody = [
            "httpStatus": 400,
            "errors": [
                [
                    "code": "INVALID_DEVICE",
                    "description": "Bad request for invalid device",
                    "id": "0",
                    "field": nil
                ]
            ]
]
<my interaction>
.willRespondWith(status: 400, headers: nil, body: errorResponseBody)
```

EDIT: It's actually much simpler:

```
<my interaction>
.willRespondWith(status: 400, headers: nil, body: ["foobar": nil])
```

# 🤔 Expected Results

Calling interaction API will return an http status code 400, with the JSON response body

# 😲 Actual Results

Calling interaction API logs message "Can not prepare a Response with non-encodable data!", and returns http status code 200 with no body.

## 🌳 Logs

"Can not prepare a Response with non-encodable data!"

I tried switching `nil` to NSNull() in the dictionary with no better results. Is there some other way I need to be representing an interaction with a nil field? 

Note: this interaction worked fine in PactConsumerSwift, which is what I"m converting from.

**Comment by tsfischer** [comment]
I moved on to mock another interaction, and got hit by the same issue. Here's another sample json, full of "nulls", that I need to mock out. How do I do this in SwiftPact?

```
[
  {
    "id": 1,
    "displayName": "Bookmark 1",
    "icon": {
      "id": 8,
      "imageUrlOriginal": "https://profile.1.icon1.url3",
      "imageUrl300": null,
      "imageUrl512": null
    },
    "description": "This is the description for Bookmark 1.",
    "url": "https://www.foo.com",
    "isDisplayInBrowser": true,
    "priority": 89
  },
  {
    "id": 2,
    "displayName": "Bookmark 2",
    "icon": {
      "id": 9,
      "imageUrlOriginal": "https://profile.2.icon1.url3",
      "imageUrl300": "https://profile.2.icon2.url",
      "imageUrl512": "https://profile.2.icon3.url"
    },
    "description": "This is the description for Bookmark 2.",
    "url": "http://localhost:3000/bookmark1.html",
    "isDisplayInBrowser": false,
    "priority": 12
  },
  {
    "id": 3,
    "displayName": "Bookmark 3",
    "icon": {
      "id": 10,
      "imageUrlOriginal": "https://profile.3.icon1.url3",
      "imageUrl300": "https://profile.3.icon2.url",
      "imageUrl512": "https://profile.3.icon3.url"
    },
    "description": "This is the description for Bookmark 3.",
    "url": "https://com.moo.bar",
    "isDisplayInBrowser": true,
    "priority": 89
  },
  {
    "id": 4,
    "displayName": "Bookmark 4",
    "icon": null,
    "description": "This is the description for Bookmark 4.",
    "url": "https://com.moo.bar",
    "isDisplayInBrowser": false,
    "priority": 89
  },
  {
    "id": 5,
    "displayName": "Bookmark 5",
    "icon": {
      "id": 11,
      "imageUrlOriginal": "https://profile.5.icon1.url3",
      "imageUrl300": "https://profile.5.icon2.url",
      "imageUrl512": "https://profile.5.icon3.url"
    },
    "description": "This is the description for Bookmark 5.",
    "url": "https://com.moo.bar",
    "isDisplayInBrowser": true,
    "priority": 33
  },
  {
    "id": 6,
    "displayName": "Bookmark 6",
    "icon": {
      "id": 12,
      "imageUrlOriginal": "https://profile.6.icon1.url3",
      "imageUrl300": "https://profile.6.icon2.url",
      "imageUrl512": "https://profile.6.icon3.url"
    },
    "description": "This is the description for Bookmark 6.",
    "url": "https://com.moo.bar",
    "isDisplayInBrowser": false,
    "priority": 45
  }
]
```

**Comment by surpher** [comment]
You should use a `Matcher.MatchNull()` instead of setting `nil`.

**Comment by tsfischer** [comment]
Thanks much for the info! Sorry I missed `MatchNull()` in the wiki. Might be a good example to include in the readme... I didn't make the connection that Matcher would handle this but that makes perfect sense now.

Really enjoying this library and that's why I'm hoping to convert from PactConsumerSwift. Thanks for your work.

**Comment by surpher** [comment]
All good. There are definitely a lot of rough edges and bugs still that will only be found and ironed out when the framework is actually used. So feel free to raise any issues you find. Also, it is only me working on this in my free time and it is all open source so any help is appreciated either with raising bugs, fixing/implementing things and even just raising feature requests.
