### ISSUE TITLE
PactSwift doesn't build on CI with SPM

### ISSUE THREAD

**Issue by atkinsa1** [surpher/PactSwift#83]
# 🗣 Context

Hi there,
We're running into a known issue with XCode 13 and PactSwift when installed via SPM on our CI. (Strangely enough this works fine when building locally).

# 💬 Narrative

When I install PactSwift as a package dependency, when compiling, the build complains that it can't import module PactSwiftMockServer.
I'm guessing that this is the known issue in xcode 13 described in the release notes:
```Using Swift packages with binary targets may result in a “no such module” error when attempting to import the module of a binary target. (77465707)```

In order to resolve we have temporarily built PactSwift as an xcframework and linked it manually, but obviously this is less than ideal.

Would it be possible to include PactSwiftMockServer so it is not a SPM dependency?

Obviously we have a workaround so this is not urgent, and it may get fixed in an upcoming xcode. I just wanted to make you aware.

Thank you!

**Comment by surpher** [comment]
There is a known bug in SPM where this can occur. It happens when a dependency pulls in a binary dependency. This is the case here where `PactSwift` depends on `PactSwiftMockServer` which is vended as a binary.

See [https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes) and search for `77465707`.

**Comment by surpher** [comment]
Apparently this has been resolved in Xcode 13.2 Beta 2:

> Resolved in Xcode 13.2 Beta 2:
> Resolved an issue where Swift packages with binary targets sometimes failed with a “no such module” error when attempting to import the module of a binary target. (77465707)

https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2-release-notes

If you could, can you give it a spin and see if it is still failing? I for some reason haven't hit this issue. I pretty much exclusively use GitHub actions and Buildkite with our own Mac Mini agent.
