### ISSUE TITLE
Add the eachKeyLike matcher

### ISSUE THREAD

**Issue by luizesramos** [surpher/PactSwift#86]
# 🗣 Context

The current Pact DLS defines the `eachKeyLike` Matcher [with an example here](https://docs.pact.io/implementation_guides/jvm/consumer#matching-any-key-in-a-map)

The [Java implementation of the Matcher](https://javadoc.io/static/au.com.dius/pact-jvm-consumer-java8_2.12/3.6.5/io/pactfoundation/consumer/dsl/LambdaDslObject.html#eachKeyLike--
) and describes `eachKeyLike` as:

```
Accepts any key, and each key is mapped to a map that must match the 
following/provided object definition Note: this needs the Java system property 
"pact.matching.wildcard" set to value "true" when the pact file is verified.
```

[`pact-js` implementation](https://github.com/pact-foundation/pact-js/blob/feat/v3.0.0/src/v3/matchers.ts#L39) of `eachKeyLike` matcher.

# 💬 Narrative

When the Producer issues a response containing a dictionary with one or more Keys
I want to be able to validate the type and format of the Values in the dictionary without knowing the Keys
So that I can add or remove values from the Producer's dictionary without the Consumer flagging a contract issue.

# 📝 Notes

# 🏗 Design

Example: this service response
```
{
  "abc": { "field1": "value1", "field2": 123 },
  "xyz": { "field1": "value2", "field2": 456 }
}
```

Could be validated with
```
Matcher.eachKeyLike([
  "field1":  Matcher.somethingLike("a string"),
  "field2": Matcher.somethingLike(0)
])
```

Note: the response validation is possible without knowing the keys "abc" and "xyz" in the service response above.

# ✅ Acceptance Criteria

**GIVEN** a dictionary populated with key-value pairs
**WHEN** the eachKeyLike matcher is applied on the dictionary
**THEN** the broker will not make assertions on the dictionary key, only on the values.

# 🚫 Out of Scope

[Regex validation for the keys](https://docs.pact.io/implementation_guides/jvm/consumer#matching-any-key-in-a-map). We can create a follow-up  issue for that, if the DSL requires it.

**Comment by surpher** [comment]
`Matcher.EachKeyLike(_: value:)` has been added to PactSwift on branch [`feature/matcher-each-key-like`](https://github.com/surpher/PactSwift/tree/feature/matcher-each-key-like). This is the first MVP to support this. In the future might find some more time to allow different variations of the struct's `init` (eg: passing in a dictionary). For now, this should suffice.

For the following response during consumer testing where "abc" and "xyz" should be considered as wildcards at provider verification:

```json
{
  "abc": { "field1": "value1", "field2": 123 },
  "xyz": { "field1": "value2", "field2": 456 }
}
```

use the `EachKeyLike` matcher as:

```swift
.willRespondWith(
  status: 200,
  body: [
    Matcher.EachKeyLike("abc", value: [ 
      "field1": Matcher.somethingLike("value1"),
      "field2": Matcher.IntegerLike(123)
    ]),
    Matcher.EachKeyLike("xyz", value: [
      "field1": Matcher.somethingLike("value2"),
      "field2": Matcher.IntegerLike(456)
    ])
  ]
)
```

**Comment by surpher** [comment]
Bare with me as I just noticed it isn't working correctly.
