### ISSUE TITLE
Allow to merge with existing pact file

### ISSUE THREAD

**Issue by abendt** [surpher/PactSwift#88]
# 🗣 Context

We want to have pact tests in separate source files that describe interactions for the same consumer/provider 

PactSwift seems to overwrite any existing pact file. It would be nice if there was an option that allows to merge with
an existing pact (similiar to the pact-jvm-consumer https://docs.pact.io/implementation_guides/jvm/consumer/junit#forcing-pact-files-to-be-overwritten-365) 

# 💬 Narrative

Given an existing pact file for a specific consumer/provider
When  running a pact consumer test for the same consumer/provider
I want the result of the second run to be merged into the existing pact file
So that i end up with one pact file describing all interactions

# 📝 Notes

* pact-jvm-consumer: https://docs.pact.io/implementation_guides/jvm/consumer/junit#forcing-pact-files-to-be-overwritten-365
* this seems to be the relevant line: https://github.com/surpher/PactSwiftMockServer/blob/main/Sources/MockServer.swift#L224 (last param _true_)

# 🏗 Design

The `pact-ffi` interface `int32_t pactffi_write_pact_file(int32_t mock_server_port, const char *directory, bool overwrite);` already supports merge (by default) and overwriting a pact file. 

- Add a convenience init `PactSwift.MockService.init(consumer: provider: scheme: writePactTo: overwrite:)` with the optional `overwrite` argument set to `false` as to merge as a default,
- Track the immutable state for `overwrite` in a `private let` (similar to `pactsDirectory`)
- When creating a `MockServer` object when finalising the Pact tests (triggering `pact-ffi` to write the file) init it with `overwrite` parameter.
- Access the immutable `private let overwrite` value in func dealing with [`pact-ffi`](https://github.com/surpher/PactSwiftMockServer/blob/9a0933140fdd07a31f08f1d251803abb37c3be23/Sources/MockServer.swift#L224) `writePactContractFile(port: completion:)`
- A new version of `PactSwiftMockServer` and a generated XCFramework binary needed to vend via SPM
- A new version of `PactSwift`

# ✅ Acceptance Criteria

**GIVEN** ...
**WHEN** ...
**THEN** ...

# 🚫 Out of Scope

**Comment by surpher** [comment]
That's a good request. Thanks for raising it.
Indeed `PactSwift` is forcing an overwrite on each test run. `pact-ffi` already supports the merging of existing Pact files and the update to `PactSwift` and `PactSwiftMockService` should be an easy enough job. It just happens it needs code changes in two repos.

The Design part has been added to the issue and hopefully should be clear enough for someone to tackle it? Otherwise it will have to wait for a couple of weeks for me to pick it up.

**Comment by surpher** [comment]
Available from [PactSwift `v0.12.1`](https://github.com/surpher/PactSwift/releases/tag/v0.12.1) with combination of PactSwiftMockServer `v0.3.8`.
