### ISSUE TITLE
Unable to run real device — Pactswift

### ISSUE THREAD

**Issue by Avengers-19** [surpher/PactSwift#91]
Hi,
We are importing the pactswift for our project and we are not able to create the pact contract file in pacts folder.
Whereas the pact contract file is created while running on the simulator but not creating the file when we running on the real device.  Below is the error we are getting,
failed - Mock Server Error: Failed to write Pact contract to file.
failed - Mock Server Error: Failed to write Pact contract to file.

**Comment by surpher** [comment]
That is the expected behaviour. 

The framework is limited to write to the disk of the device it is running on, which in your case would be the iOS devices disk and not you mac. 

I'm just about to release a version that would write an info message into the console when running on a device.

**Comment by surpher** [comment]
This is now live with version `v0.12.1`. When running on a physical device the writing of the pact contract file will be skipped, will not fail the tests and will debug console will print something like this:

```
Test Suite 'Selected tests' started at 2022-06-01 11:19:12.646
Test Suite 'AnimalClientTests.xctest' started at 2022-06-01 11:19:12.647
Test Suite 'AnimalClientTests' started at 2022-06-01 11:19:12.648
Test Case '-[AnimalClientTests.AnimalClientTests testGetsAnimals]' started.
[INFO]: Running on an iOS device. Writing Pact interaction into a contract skipped.
Test Case '-[AnimalClientTests.AnimalClientTests testGetsAnimals]' passed (0.505 seconds).
Test Suite 'AnimalClientTests' passed at 2022-06-01 11:19:13.154.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.505 (0.506) seconds
Test Suite 'AnimalClientTests.xctest' passed at 2022-06-01 11:19:13.154.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.505 (0.507) seconds
Test Suite 'Selected tests' passed at 2022-06-01 11:19:13.155.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.505 (0.508) seconds
```
