### ISSUE TITLE
PactSwift how to build on CI 

### ISSUE THREAD

**Issue by Avengers-19** [surpher/PactSwift#92]
PactSwift:
   we are unable to generate pact file while running on real time device, so we planned to generate pact file using CI.
   Please share the information about how to generate and push the Pact file using CI.

**Comment by surpher** [comment]
Pact contract files will not be generated if running on a physical device due to `pact_ffi` writing to local disk.

Pact contract files will not be generated if the tests fail.

Where the Pact contracts get written to is explained here: https://github.com/surpher/PactSwift#generated-pact-contracts

**Comment by Avengers-19** [comment]
We are going to publish pact file using pipeline 
In android using gradlew to run  

Examble code:
       run: chmod +x gradlew 
       name: Run Tests
        run: ./gradlew test --no-daemon -q
       name: Push pacts to broker

In iOS swift how to publish the pact file using pipeline

**Comment by surpher** [comment]
See https://github.com/surpher/PactSwift#sharing-pact-contracts
